### ISSUE TITLE
set_names_from_template does not work with CSV

### ISSUE THREAD

**Issue by alon-sarid** [sarid-ins/saridr#7]
Hi Adi.

the names will not change if the template is of type CSV

**Comment by Perach-Hen** [comment]
I tried the following example with some changes in the names of the columns and no error was occurred:
mtcars %>% make_header_template(path = "mtcar_headers.csv")
mtcars %>% set_names_from_template(path = "mtcar_headers.csv")

**Comment by adisarid** [comment]
@alon-sarid can you provide a minimum reprex for the bug?

Thnx.
